### ISSUE TITLE
How to use Ainu Segmenter

### ISSUE THREAD

**Issue by KoichiYasuoka** [karol-nowakowski/MiNgMatchSegmenter#1]
Please show the usage and installation of MiNgMatchSegmenter.

**Comment by karol-nowakowski** [comment]
There's no need to install anything, just download the script and enter the following command:
```
python MiNgMatchSegmenter.py -t ngrams.txt -i input.txt -o output.txt
```
where `ngrams.txt` is a tab-delimited file with your n-gram data.
For more details, please refer to the [README ](https://github.com/karol-nowakowski/MiNgMatchSegmenter/blob/master/README.md) file (I added some explanations) and the paper.
In case of any problems, feel free to contact me.

**Comment by KoichiYasuoka** [comment]
Thank you @karol-nowakowski and I will follow the README.
